In [1]:
"""
pip install pandas
pip install wrds
"""
import pandas as pd
import wrds

In [2]:
conn = wrds.Connection()

WRDS recommends setting up a .pgpass file.
You can create this file yourself at any time with the create_pgpass_file() function.
Loading library list...
Done

In [48]:
q = """ 
    SELECT * 
    FROM 
        tr_ds_equities.wrds_ds_indexconstmerged_mth as a
    WHERE 
        a.indexlistintcode = 8015
    """

In [49]:
df = conn.raw_sql(q)
df.head()

Empty DataFrame
Columns: [indexlistintcode, indexlistmnem, indexlistdesc, constintcode, date_, close_, weight, fffactor, partfffactor, shares, ffshares, mktval, ffmktval, adjfactor, capfactor, infocode, permitlevelcode, liststatuscode, ldb, licflag]
Index: []

In [47]:
df.groupby('date_').agg({"constintcode":'count'})

            constintcode
date_
2022-01-31          1000
2022-02-28          1000
2022-03-31          1000
2022-04-29          1000
2022-05-31          1000
2022-06-30          1000
2022-07-29          1000
2022-08-31          1000
2022-09-30          1000
2022-10-31          1000
2022-11-30          1000
2022-12-30          1000
2023-01-31          1000
2023-02-28          1000
2023-03-31          1000
2023-04-28          1000
2023-05-31          1000
2023-06-30          1000
2023-07-31          1000
2023-08-31          1000
2023-09-29          1000
2023-10-31          1000
2023-11-30          1000
2023-12-29          1000
2024-01-31          1000
2024-02-29          1000
2024-03-29          1000
2024-04-30          1000
2024-05-31          1000
2024-06-28          1000
2024-07-31          1000
2024-08-30          1000
2024-09-30          1000
2024-10-31          1000
2024-11-29          1000
2024-12-31          1000